// This file was autogenerated by calcdeps.js
goog.addDependency('../../node_modules/closure-dom/src/dom.js', ['dom'], []);
goog.addDependency('../../src/descriptors.js', ['fontface.Descriptors'], []);
goog.addDependency('../../src/observer.js', ['fontface.Observer'], ['fontface.Ruler','dom']);
goog.addDependency('../../src/ruler.js', ['fontface.Ruler'], ['dom']);
