// This file was autogenerated by calcdeps.js
goog.addDependency("../../src/descriptors.js", ["fontface.Descriptors"], []);
goog.addDependency("../../src/dom.js", ["fontface.dom"], []);
goog.addDependency("../../src/main.js", [], ["fontface.Observer"]);
goog.addDependency("../../src/observer.js", ["fontface.Observer"], ["fontface.Ruler","fontface.Promise","fontface.dom"]);
goog.addDependency("../../src/promise.js", ["fontface.Promise"], []);
goog.addDependency("../../src/ruler.js", ["fontface.Ruler"], ["fontface.dom"]);
