// This file was autogenerated by calcdeps.js
goog.addDependency("../../node_modules/closure-dom/src/dom.js", ["dom"], []);
goog.addDependency("../../src/css.js", ["fontface.Css"], []);
goog.addDependency("../../src/descriptors.js", ["fontface.Descriptors"], []);
goog.addDependency("../../src/observer.js", ["fontface.Observer"], ["fontface.Ruler","dom","lang.Promise"]);
goog.addDependency("../../src/ruler.js", ["fontface.Ruler"], ["dom"]);
goog.addDependency("../../node_modules/promis/src/async.js", ["lang.async"], []);
goog.addDependency("../../node_modules/promis/src/promise.js", ["lang.Promise"], ["lang.async"]);
